name: CI

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: nikeee/docfx-action@v0.1.0
      name: Build Documentation
      with:
        args: docfx.json
    - name: Commit files
      run: |
        cp -r ./_site/* ./docs/
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        git commit -m "Rebuild docs" || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}